### ISSUE TITLE
Linking capability Issue in Webform

### ISSUE THREAD

**Issue by asvensen** [CuBoulder/express_admin#15]
In the markup options in the form builder, the option to add or edit a link in the WYSIWYG does not work. This can be seen on https://live-ucbdev-sandbox-webcentral-101.pantheonsite.io/form/drupal-10-migration-path-form. If you try to edit the form component "Which migration path would you like to take for this site?" you can't change the link in the text area of that form component. This happened when trying to use various markup options.

**Comment by timurtripp** [comment]
Can't reproduce on my end. @asvensen is this still a problem?

**Comment by asvensen** [comment]
This is all working just fine now! Thank you for looking into it.

**Comment by timurtripp** [comment]
No problem! With a [related issue](https://www.drupal.org/project/drupal/issues/3453320) for this breaking on a future version of Drupal (10.3) found and fixed as well I'll mark this as resolved.

**Comment by timurtripp** [comment]
Do let us know if you experience this again though.

**Comment by asvensen** [comment]
Good thinking! Thank you!
