### ISSUE TITLE
Sidebar Collapse Button

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/express_admin#16]
We added in a custom button to collapse the sidebar in the edit view...

However the sidebar is now no longer a sidebar but displayed below the input fields for the node.  So this functionality is now no longer needed and should be removed.

**Comment by timurtripp** [comment]
Need to find out whether this was an intentional change or just a bug. To me it seems like a bug. Or possibly we've broken the sidebar with our own changes.

**Comment by timurtripp** [comment]
Not seeing anything about this in the 10.3 release notes so it doesn't appear to be an intentional change.

**Comment by timurtripp** [comment]
Closing in favor of #17
