### ISSUE TITLE
Add image button is hard to see

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express_admin#9]
When adding an image to the media library, the save/insert button is difficult to see:

<img width="1401" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/b097d5db-2526-4b19-919d-1a00cb13c71e">

<img width="1401" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/46b00c11-2f1a-4cc9-853f-055ef83f1ef7">

**Comment by timurtripp** [comment]
Duplicate issue: CuBoulder/express_admin#8

**Comment by timurtripp** [comment]
This did help me actually reproduce the issue though, thanks.
